language: php

sudo: false

cache:
  directories:
      - node_modules
      - vendor
      - $HOME/.composer/cache

env:
  - DB_DATABASE=protecms_test
  - DB_USERNAME=travis
  - DB_PASSWORD=
  - MAIL_DRIVER=log

php:
  - '7.0'
  - '7.1'

before_script:
  - mysql -e 'create database protecms_test'
  - npm install
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan protecms:seeddevdata

script:
  - gulp
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop
    - feature/travisci

notifications:
  email: 'web@protecms.com'