language: php

sudo: false

cache:
  directories:
      - node_modules
      - vendor
      - $HOME/.composer/cache

node_js:
  - "node"

php:
  - '7.0'
  - '7.1'

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - mysql -e 'create database protecms_test'
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - composer self-update
  - composer install --no-interaction

before_script:
  - cp .env.travis .env
  - php artisan key:generate

script:
  - gulp
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop
    - feature/travisci